server:
  port: 30120

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/embedded/*Mapper.xml
  config-location: classpath:jpaConfig-embedded.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: h-dict
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    encoding: UTF-8
  mvc:
    interceptors:
      mdc:
        enabled: true
      api-safe:
        enabled: false
      resource-handler-registry:
        entries:
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
        enabled: true
      login:
        enabled: false
        cookie-max-age-sec: 1800
        dialect: embedded
        include-urls:
          - "/hbq969-sm/**"
          - "/hbq969-dict/**"
          - "/hbq969-tabula/**"
          - "/common/encrypt/**"
          - "/ui-gw/**"
          - "/**/doc.html"
          - "/**/swagger-ui.html"
          - "/**/api-docs"
        exclude-urls:
          - "/**/error"
          - "/common/health"
          - "/hbq969-sm/index.html"
          - "/hbq969-sm/**/*.js"
          - "/hbq969-sm/**/*.css"
          - "/hbq969-sm/**/*.png"
          - "/hbq969-sm/**/*.jpg"
          - "/hbq969-sm/**/*.map"
          - "/hbq969-sm/**/*.ico"
          - "/hbq969-sm/**/login"

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:mem:local
      driver-class-name: org.h2.Driver
      username: foo
      password: ENC(2HRE3Jhuz6IfiD8L7orn4flpXNPTWLhH4u6lH/i0SWf8jXh3tNGQG++plhHmJN3F)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123456

swagger:
  base-package: com
  api-info:
    title: web应用Restful API
    description: web应用Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

dict:
  enabled: true
  reload:
    cron: 0 */30 * * * *
  map-key-prefix: fmt

encrypt:
  config:
    enabled: true
  restful:
    enabled: true
    aes:
      key: DC2EE8931E434A44
      show-log: true

advice:
  log:
    enabled: true
  restful-limit:
    enabled: true

tabula:
  enabled: false
  dialect: mysql
  schema: openstack

operlog:
  enabled: false
  use-default-collect-policy: false
  policy: mysql
  thread-num: 1
  batch-size: 50
  batch-timeout-mills: 5000
  queue-capacity: 5000
  table-name: log_dict